Banker/Controllers/ProsesInfoController.cs
using Banker.Repository;
using Banker.UIModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Banker.Controllers
{
    public class ProsesInfoController : Controller
    {
        public ProsesInfoController()
        {
            rep = new Pos_Ins_UserRepository();
        }

        Pos_Ins_UserRepository rep { get; }

       

        public IActionResult AssingeInfo()
        {
            var roles=User.Claims.Where(x => x.Type == System.Security.Claims.ClaimTypes.Role).Select(x => x.Value).ToList();
            var model = new UIProsInfo();

            var list = rep.GetPosInsUser(roles,getUserId());
            model.AssingePosision= list.Where(x=>x.UserId==0).ToList();
            model.AssingeMe = list.Where(x => x.UserId == getUserId()).ToList();
            return View(model);
        }

        public IActionResult Assinge(int id)
        {
            string[] clms = {"UserId" };
            object[] vals = { getUserId() };
            var b=rep.Update(clms, vals,id);
            var (p, bb) = rep.GetByColumNameFist("Id", id);
            return RedirectToAction(p.Step, p.PosesName,new {id=p.ProsessId});
        }


        public IActionResult ProsessReport()
        {
            return View();
        }

        public IActionResult SearchIns(UIReprotProsess model)
        {
            if (string.IsNullOrEmpty(model.ProsesName)) return View("ProsessReport",model);
            model.Response=rep.GetProsess(model);
            return View("ProsessReport", model);
        }
        [Authorize]
        public IActionResult MyProsess()
        {            
            var (list,b)=rep.GetByColumName("UserId", getUserId());
            if (!b) RedirectToAction("Index", "Home");
            var t = list;
            return View(list);
        }

        int getUserId()
        {
            int userId = 0;
            Int32.TryParse(User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value, out userId);
            return userId;
        }
    }
}

Banker/Controllers/UserInfoController.cs
using Banker.Tools;
using Banker.UIModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Models.APIResponseModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Banker.Controllers
{
    public class UserInfoController : Controller
    {
        public UserInfoController(IConfiguration config)
        {
            Config = config;
        }

        public IConfiguration Config { get; }

        public async Task<IActionResult> Profile()
        {
            var token = User.Claims.First(x => x.Type == "Token").Value;
            int id=0;
            Int32.TryParse(User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value,out id);
            AppUserResponse result = new AppUserResponse();
            if (id == 0) RedirectToAction("Index", "Home");
            using (HttpClient client =new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
                using (var response=await client.GetAsync(ServiceURL.GetURL(Config) + "Home/GetUserById/"+id.ToString()))
                {
                    var content=await response.Content.ReadAsStringAsync();
                    result = JsonConvert.DeserializeObject<AppUserResponse>(content);
                }
            }
            if (result == null) return View();
            var model = new UIAppUser {
                Email = result.User.Email,
                Id = result.User.Id,
                Name = result.User.Name,
                userClaims = result.UserClaims
            };
            return View(model);
        }
    }
}

Banker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/tmpl/fontawesome-free/css/all.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/tmpl/dist/css/adminlte.min.css">
    @RenderSection("CSS", required: false)
</head>
<body class="hold-transition sidebar-mini  sidebar-collapse">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Home" class="nav-link">Əsas </a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <a id="StartProses" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Start</a>
                        <ul aria-labelledby="StartProses" class="dropdown-menu border-0 shadow">
                            @foreach (var item in Banker.StaticObj.AllProsess.Prosess)
                            {
                                <li>
                                    <form method="post">
                                        <button type="submit" asp-action="Start" asp-controller="@item" class="dropdown-item ">
                                            <p>@item</p>
                                        </button>
                                    </form>
                                </li>
                            }
                        </ul>
                    </li>
                }
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="AssingeInfo" asp-controller="ProsesInfo">
                            <i class="far fa-bell"></i>
                            <span class="badge badge-danger navbar-badge">1</span>
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" href="#">
                            <i class="far fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <a href="#" class="dropdown-item">
                                <!-- Message Start -->
                                <div class="media">
                                    <img src="~/tmpl/dist/img/avatar5.png" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                    <div class="media-body">
                                        <p class="dropdown-item">
                                            @User.Identity.Name
                                        </p>
                                    </div>
                                </div>
                                <!-- Message End -->
                            </a>
                            <a asp-action="Profile" asp-controller="UserInfo" class="dropdown-item">
                                <i class="far fa-sign-out-alt"></i>
                                <p>Profil</p>
                            </a>
                            <a asp-action="Logout" asp-controller="Home" class="dropdown-item">
                                <i class="far fa-sign-out-alt"></i>
                                <p>Çıxış</p>
                            </a>

                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a asp-action="Login" asp-controller="Home" class="nav-link">Giriş</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Register" asp-controller="Home" class="nav-link">Qeydiyyat</a>
                    </li>
                }


            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-action="Index" asp-controller="Home" class="brand-link">
                <img src="~/tmpl/dist/img/bank.png" alt="BPM" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">BPM</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="#" class="nav-link ">
                                <i class="nav-icon fas fa-user-tie"></i>
                                <p>
                                    Prosess monitor
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="ProsesInfo" asp-action="MyProsess" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>My Prosess</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="ProsessReport" asp-controller="ProsesInfo" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>All Prosess</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-handshake-alt-slash"></i>
                                <p>
                                    Object <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <div class="content-wrapper">
            @RenderBody()
        </div>




        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Yaradilib: &copy; 2020 Mirze.</strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/tmpl/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/tmpl/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/tmpl/dist/js/adminlte.min.js"></script>

    @RenderSection("Script", required: false)

</body>
</html>

Banker/Views/Shared/_ProsessLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/tmpl/fontawesome-free/css/all.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/tmpl/dist/css/adminlte.min.css">
    @RenderSection("CSS", required: false)
</head>
<body class="hold-transition sidebar-mini sidebar-collapse">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" href="#">
                            <i class="far fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <a href="#" class="dropdown-item">
                                <!-- Message Start -->
                                <div class="media">
                                    <img src="~/tmpl/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                    <div class="media-body">
                                        <p class="dropdown-item">
                                            @User.Identity.Name
                                        </p>
                                    </div>
                                </div>
                                <!-- Message End -->
                            </a>
                            <a asp-action="Logout" class="dropdown-item">
                                <i class="far fa-sign-out-alt"></i>
                                <p>Çıxış</p>
                            </a>

                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a asp-action="Login" asp-controller="Home" class="nav-link">Giriş</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Register" asp-controller="Home" class="nav-link">Qeydiyyat</a>
                    </li>
                }


            </ul>
        </nav>
        <!-- /.navbar -->
       
        <div class="content">
            @RenderBody()
        </div>


        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Yaradilib: &copy; 2020 Mirze.</strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/tmpl/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/tmpl/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/tmpl/dist/js/adminlte.min.js"></script>

    @RenderSection("Script", required: false)

</body>
</html>